yarnPath: .yarn/releases/yarn-2.2.2.cjs

packageExtensions:
    "@babel/parser@*":
        dependencies:
            "@babel/types": "*"
    "taskr@*":
        peerDependenciesMeta:
            "@taskr/clear":
                optional: true
            "@taskr/esnext":
                optional: true
            "@taskr/watch":
                optional: true
