yarnPath: .yarn/releases/yarn-2.2.2.cjs

packageExtensions:
    "@babel/parser@*":
        dependencies:
            "@babel/types": "*"
    "@firebase/firestore@*":
        dependencies:
            "protobufjs": "*"
    "babel-plugin-styled-components@*":
        peerDependencies:
            react-is: "*"
    "taskr@*":
        peerDependenciesMeta:
            "@taskr/clear":
                optional: true
            "@taskr/esnext":
                optional: true
            "@taskr/watch":
                optional: true
